[package]
name = "commune"
version = "0.0.1"
authors = ["Justin Austin <justin@justincaustin.com>"]
edition = "2018"

[dependencies]
itertools = "^0.8"
rand = "^0.6"
strum = "^0.13"
strum_macros = "^0.13"